import Head from 'next/head'
import NewNav from '../components/NewNav/newNav';
import styles from '../styles/AboutMe.module.scss';
import Link from 'next/link';
import ContactForm from '@/components/Contact/contactForm';


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.page}>
        <div className={styles.left_side}>
            <h1 className={styles.page_name}>ABOUT ME</h1>
            <div className={styles.left_content}>
                <p className={styles.left_p}>
                    As a front-end engineer, I have a strong passion for coding, gaming, anime, and sports. 
                    My days are primarily spent programming, exploring new programming languages, and avidly following my favorite teams, the Braves, Falcons, and Hawks 
                    or indulging in my love for anime. I'm currently watching on the <i>"Hell's Paradise"</i> – definitely a good watch. 
                </p>
            </div>
        </div>
        <div className={styles.right_side}>
                <div className={styles.textbox}>
                    <p className={styles.p}>
                        As a front-end engineer, I have a strong passion for coding, gaming, anime, and sports. 
                        My days are primarily spent programming, exploring new programming languages, and avidly following my favorite teams, the Braves, Falcons, and Hawks 
                        or indulging in my love for anime. I'm currently watching on the <i>"Hell's Paradise"</i> – definitely a good watch. 
                    </p>
                </div>
                <div className={styles.img_container1}>
                    <img src="./images/black-guy.webp" alt="" className={styles.img1} />
                </div>
                <div className={styles.img_container2}>
                    <img src="./images/sea.webp" alt="" className={styles.img2} />
                </div>
                <div className={styles.img_container3}>
                    <img src="./images/swimming-lady.webp" alt="" className={styles.img3} />
                </div>
        </div>
        <NewNav mobileBg='#FFDDBD' logoTheme='black' navTextColor='black'/>
      </section>
    </>
  )
}