import Head from 'next/head'
import NewNav from '../components/NewNav/newNav';
import styles from '../styles/Contact.module.scss';
import Link from 'next/link';
import ContactForm from '@/components/Contact/contactForm';


export default function Contact() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.page}>
      <video  className={styles.video} autoPlay muted loop>
         <source src="./videos/contact.mp4" type="video/mp4" />
      </video>
        <main className={`${styles.main} `}>
            <ContactForm/>
        </main>
        <NewNav mobileBg='#23292Aa1' navTextColor='white'/>
      </section>
    </>
  )
}