import Head from 'next/head'
import NewNav from '../components/NewNav/newNav';
import styles from '../styles/Contact.module.scss';
import Link from 'next/link';
import ContactForm from '@/components/Contact/contactForm';


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.page}>
        <main className={`${styles.main} flex-column-reverse align-items-center flex-lg-row w-md-100`}>
        <div className={styles.left_side}>
            <ContactForm/>
        </div>
        <div className={styles.right_side}>
            <h1 className={styles.page_name}>CONTACT</h1>
        </div>
        </main>
        <NewNav mobileBg='#23292A' mobileTextColor='white'/>
      </section>
    </>
  )
}