import Head from 'next/head'
import Image from 'next/image';
import NewNav from '../components/NewNav/newNav';
import styles from '../styles/Home.module.scss';
import Link from 'next/link';
import Works from './works';
import Skills from './skills';
import AboutMe from './about-me';
import Contact from './contact';


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <section id='home' className={styles.home}>
        <div className={styles.hero}>
          <h3 className={styles.small_title}>SOFTWARE ENGINEER</h3>
          <h1 className={styles.big_title}>MAKYIA BONNER</h1>
        </div>
        <div className={styles.scrollIntoView_div}>
          <div className={styles.scrollIntoView_box}>
            <div className={styles.scrollIntoView_ball}></div>
          </div>
          <span className={styles.scrollIntoView}>SCROLL TO VIEW</span>
        </div>
        <NewNav/>
      </section>
      <section id='works'><Works/></section>
      <section id='skills'><Skills/></section>
      <section id='about me'><AboutMe/></section>
      <section id='contact'><Contact/></section>
    </>
  )
}
