import NewNav from '@/components/NewNav/newNav';
import Head from 'next/head';
import { imageConfigDefault } from 'next/dist/shared/lib/image-config';
import styles from '../styles/Skills.module.scss';

export default function Skills(){
    const skills = [
        {id:'react', pic:'./icons/white-react.svg', alt:'react'},
        {id:'html', pic:'./icons/white-html.svg', alt:'html'},
        {id:'css', pic:'./icons/white-css.svg', alt:'css'},
        {id:'sass', pic:'./icons/white-sass.svg', alt:'sass'},
        {id:'javascript', pic:'./icons/white-js.svg', alt:'javascript'},
        {id:'bootstrap', pic:'./icons/white-bootstrap.svg', alt:'bootstrap'},
        {id:'typescript', pic:'./icons/white-ts.svg', alt:'typescript'},
        {id:'nextjs', pic:'./icons/white-nextjs.svg', alt:'nextjs'}
    ]
    const techStack = skills.map((skill) => {
        return <img key={skill.id} className={styles.tech_logo} src={skill.pic} alt={skill.alt} />
    })
    return(
        <>
         <Head>
            <title>Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className={styles.page}>
            <section className={styles.main_content}>
                <div className="d-flex flex-column mx-auto my-4">
                    <div className={styles.title_div}>
                        <span className={styles.span}>MY SKILLS</span>
                        <h1 className={styles.techTitle}>Technologies.</h1>
                    </div>
                    <div className={styles.main_grid}>
                        {techStack}
                    </div>
                </div>
            </section>
            <NewNav navTextColor='white' mobileBg='black'/>
         </main>
        </>
    )
}